name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: apt install cmake g++ libsdl2-mixer-dev libsdl2-ttf-dev libsodium-dev
    - name: CNMake
      run: cd build && cmake ..
    - name: Make
      run: cd build && make -j$(nproc)
